In [1]:
import numpy as np
import pandas as pd
from sklearn.impute import SimpleImputer

In [2]:
# base de dados de admissao de alunos pra classificar se ele é admitido numa pos
db = pd.read_csv('/home/vicrrs/My_Projects/ML_projects/archives/admission.csv', delimiter=';')

# conjunto de dados (variaveis independentes)
X = db.iloc[:, :-1].values

# rotulo dos dados (variavel dependente)
y = db.iloc[:,-1].values

In [3]:
imputer = SimpleImputer(missing_values=np.nan, strategy='median')
imputer = imputer.fit_transform(X[:,1:])

In [4]:
"""
A classe LabelEncoder é usada para converter rótulos de texto ou categorias em números inteiros. 
Ela é comumente usada quando você tem dados categóricos que precisam ser transformados em uma forma 
que modelos de aprendizado de máquina possam entender
"""
from sklearn.preprocessing import LabelEncoder

In [5]:
labelencoder_X = LabelEncoder()
X[:, 0] = labelencoder_X.fit_transform(X[:, 0]) # computa a parte de rotulos
print(X)

[[6 337 118 4 4.5 4.5 9.65 1]
 [0 324 107 4 4.0 4.5 8.87 1]
 [5 316 104 3 3.0 3.5 8.0 1]
 [1 322 110 3 3.5 2.5 8.67 1]
 [8 314 103 2 2.0 3.0 8.21 0]
 [4 330 115 5 4.5 3.0 9.34 1]
 [3 321 109 3 3.0 4.0 8.2 1]
 [2 308 101 2 3.0 4.0 7.9 0]
 [7 302 102 1 2.0 1.5 8.0 0]]


In [6]:
X = X[:,1:]

In [7]:
# Valores decimais influencia no valor final do modelo, é melhor trocar para rotulos binarios(OneHotencode)
D = pd.get_dummies(X[:,0]) # computando onehotencode
X = np.insert(X, 0, D.values, axis=1) # Inserindo as colunas novas que a variavel binaria tras em X

In [8]:
print(X)

[[False False False False False False False False True 337 118 4 4.5 4.5
  9.65 1]
 [False False False False False False False True False 324 107 4 4.0 4.5
  8.87 1]
 [False False False False True False False False False 316 104 3 3.0 3.5
  8.0 1]
 [False False True False False False False False False 322 110 3 3.5 2.5
  8.67 1]
 [False False False False False False True False False 314 103 2 2.0 3.0
  8.21 0]
 [False False False True False False False False False 330 115 5 4.5 3.0
  9.34 1]
 [False True False False False False False False False 321 109 3 3.0 4.0
  8.2 1]
 [False False False False False True False False False 308 101 2 3.0 4.0
  7.9 0]
 [True False False False False False False False False 302 102 1 2.0 1.5
  8.0 0]]


In [9]:
# Dividindo o conjunto de dados em dados de treino e teste
from sklearn.model_selection import train_test_split

Xtrain, Xtest, ytrain, ytest = train_test_split(X, y, test_size=0.2)

print(Xtrain)

[[False False False False False False False True False 324 107 4 4.0 4.5
  8.87 1]
 [False False True False False False False False False 322 110 3 3.5 2.5
  8.67 1]
 [False False False False False False True False False 314 103 2 2.0 3.0
  8.21 0]
 [False False False False False False False False True 337 118 4 4.5 4.5
  9.65 1]
 [False False False False True False False False False 316 104 3 3.0 3.5
  8.0 1]
 [False False False False False True False False False 308 101 2 3.0 4.0
  7.9 0]
 [False False False True False False False False False 330 115 5 4.5 3.0
  9.34 1]]
